services:
  cloud_chatops:
    image: harbor.stfc.ac.uk/stfc-cloud/cloud-chatops
    volumes:
      - ./cloud_chatops_secrets/:/opt/cloud_chatops_secrets/
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 60
