name: Rabbit Consumer

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/Openstack-Rally-Tester.yaml"
      - "OpenStack-Rally-Tester/**"

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install pylint
      
      - name: Analyse with pylint
        run: |
          cd OpenStack-Rally-Tester && pylint rally-extract-results.py

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./OpenStack-Rally-Tester"
