name: Pynetbox Data Uploader Tests

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "pynetbox_data_uploader/**"
      - ".github/workflows/pynetbox.yaml"

jobs:
  test_and_lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd pynetbox_data_uploader
          pip install -r requirements.txt
          

      - name: Analyse with pylint
        run: cd pynetbox_data_uploader && pylint . --rcfile=.pylintrc

      - name: Run tests and collect coverage
        run: cd pynetbox_data_uploader && python3 -m pytest --cov-report xml:coverage.xml --cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./pynetbox_data_uploader/coverage.xml

