name: Rabbit Consumer Prototype

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/rabbit_consumer_prototype.yaml"
      - "OpenStack-Rabbit-Consumer/**"

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          echo "Hello World"