name: Build local helm chart
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/rabbit_consumer_chart.yaml"
      - "OpenStack-Rabbit-Consumer-Chart/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm lint OpenStack-Rabbit-Consumer-Chart --values OpenStack-Rabbit-Consumer-Chart/values.yaml --values OpenStack-Rabbit-Consumer-Chart/dev-values.yaml --strict=true

  publish:
    runs-on: ubuntu-latest
    # DO NOT MERGE
    # if: github.ref == 'refs/heads/master'
    needs:
      - helm-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: OpenStack-Rabbit-Consumer-Chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
