name: Rabbit Consumer Protoype

on:
  schedule: 
      - cron: "21 10 * * SUN-SAT" # Everyday at 10:21

jobs:
  push_dev_image_harbor:
    runs-on: ubuntu-latest
    needs: test_and_lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Set commit SHA for later
        id: commit_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push to staging project
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          context: "{{defaultContext}}:OpenStack-Rabbit-Consumer"
          tags: "harbor.stfc.ac.uk/stfc-cloud-staging/openstack-rabbit-consumer:${{ steps.commit_sha.outputs.sha_short }}"

      - name: Inform of tagged name
        run: echo "Image published to harbor.stfc.ac.uk/stfc-cloud-staging/openstack-rabbit-consumer:${{ steps.commit_sha.outputs.sha_short }}"

  push_release_image_harbor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    needs: test_and_lint
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Increment Version
        run: |
          ./version_increment.sh

      - name: Get release tag for later
        id: release_tag
        run: echo "version=$(cat OpenStack-Rabbit-Consumer/version.txt)" >> $GITHUB_OUTPUT

      - name: Check if release file has updated
        uses: dorny/paths-filter@v2
        id: release_updated
        with:
          filters: |
            version:
              - 'OpenStack-Rabbit-Consumer/version.txt'

      - name: Build and push on version change
        uses: docker/build-push-action@v3
        if: steps.release_updated.outputs.version == 'true'
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          context: "{{defaultContext}}:OpenStack-Rabbit-Consumer"
          tags: "harbor.stfc.ac.uk/stfc-cloud/openstack-rabbit-consumer:v${{ steps.release_tag.outputs.version }}"

      - name: Inform of tagged name
        if: steps.release_updated.outputs.version == 'true'
        run: echo "Image published to harbor.stfc.ac.uk/stfc-cloud/openstack-rabbit-consumer:v${{ steps.release_tag.outputs.version }}"