name: Rabbit Consumer Protoype

on:
  push:
    branches:
      - master
  schedule: 
      - cron: "12 10 * * TUE" # Every Tuesday at 10.12am
  paths:
    - 'OpenStack-Rabbit-Consumer/'

jobs:
  version_increment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Increment Version
        run: bash ${{ github.workspace }}/.github/workflows/bin/version_increment.sh

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: ${{ github.workspace }}/OpenStack-Rabbit-Consumer/version.txt
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com