name: Build local helm chart
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/rabbit_consumer_chart.yaml"
      - "charts/rabbit-consumer/**"

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Lint Helm Chart
        # Note --strict=true != --strict with the former being stricter
        run: |
          helm lint charts/rabbit-consumer --values charts/rabbit-consumer/values.yaml --values charts/rabbit-consumer/dev-values.yaml --strict=true

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - helm-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
